version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
    - "!node_modules/**"
